### ISSUE TITLE
Include cyclic color scales?

### ISSUE THREAD

**Issue by jens-daniel-mueller** [thomasp85/scico#8]
Hi Thomas,
I've no clue how much effort it takes, but would it be possible to add [Fabio's cyclic color scales](http://www.fabiocrameri.ch/colourmaps.php) to the package?
I feel they are a helpful feature for some visualization and am happy to support implementation, if I can.
Cheers
![grafik](https://user-images.githubusercontent.com/33910817/76506301-3f90cb00-644b-11ea-8fa9-8e8b7c605e1c.png)

**Comment by jens-daniel-mueller** [comment]
Hi Thomas,
did you already have time to take a look at this issue?
Would be great to have a feedback whether addition of any kind of cyclic color scales is planned.
If not, I'll have to search for alternative solutions.
Thanks for an update!
Jens

**Comment by m-clark** [comment]
There is a pull request from a few months ago that implements these (pr #7) , but it has not been accepted yet.

**Comment by thomasp85** [comment]
closed by #7
