### ISSUE TITLE
Author Specified Categorical Palettes

### ISSUE THREAD

**Issue by nlubock** [thomasp85/scico#9]
Hey thanks again for supporting the development of these amazing color palettes. The author has recently released specific categorical versions of many of the colormaps [1,2]. I was wondering if it would be possible to include these in `scico`. One challenge is `scale_color_scico_d` already exists... I'm not sure if it would be more appropriate for that function to pull from the author's categorical maps, or to make it a new function.

[1] http://www.fabiocrameri.ch/categorical.php
[2] https://zenodo.org/record/4153113 (you can see the categorical palettes specified with the suffix `S`)

**Comment by sims1253** [comment]
@thomasp85 Any possibility for an update to happen?
